spring.application.name=apigatewapi
server.port=9080


#KeyCloak

keycloak.auth.jwt-set-uri = http://localhost:9081/realms/ticketing-security-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-url=http://localhost:9081/realms/ticketing-security-realm"


# Actuator
#Activation
management.health.circuitbreakers.enabled=true

#exposer sur tout les endpoints
management.endpoints.web.exposure.include=*
#toujours afficher les details
management.endpoint.health.show-details=always

#Resilience4J
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
#le nombre de requette a verifier
resilience4j.circuitbreaker.configs.default.slidingWindowSize=8
#seuil d alert 50%, on ouvre Resilience4J
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
#Nombre niminum d appel
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=4
#le temps que le circuit reste ouvert
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
#nombre des requettes permises dans l etat semiouvert
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
#Passege de l'etat semiouvert a ouvert
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true

#Limete de delais
resilience4j.timelimiter.configs.default.timeout-duration=3s
#tentative minimal
resilience4j.retry.configs.default.max-attempts=3
#duree entre les tentatives
resilience4j.retry.configs.default.wait-duration=2s